name: test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install helmfile
        uses: helmfile/helmfile-action@v1.0.0
        with:
          helmfile-version: 0.151.0
